### ISSUE TITLE
Service does not seem to start inside container or VM

### ISSUE THREAD

**Issue by ramantalkin** [joequant/bitquant#11]
The docker container image or VM from sourceforge starts well but certain services including bitquant.service fails to start. I am using this image in KVM "http://sourceforge.net/projects/bitquant/files/bitstation/Bitstation-v0.0.4-64bit.ova/download"

Here is what i did http://imgur.com/uFFFnMP
(same were the results with docker image)
restarting the services does not solve the issue, it says "exited with code 0"

I don't know if i am missing on something or it is a bug.

**Comment by joequant** [comment]
Hi,

The VM container is now deprecated.  The preferred way of running the
system is by downloading the container joequant/bitstation from docker and
then running it with the run-docker.sh script in docker.

If you can show me where the wrong README is, I can fix it.

**Comment by ramantalkin** [comment]
yes i previously used that too, but all the ports 80, 443 and 8080 keeps on loading with no response.

**Comment by joequant** [comment]
The docker script in run-docker.sh should map the ports from the docker
machine to the local machine.  You can sudo shell-docker.sh to see if
things will run from inside the docker machine.

One typical cause of problems is if you have a firewall running and it's
blocking the docker interface.

**Comment by ramantalkin** [comment]
yes the container is exposing port 80 and 443 but it does not start loading. are the ports bind to localhost only.

**Comment by joequant** [comment]
What do you get when you access the container via port 80?

The container should bind to port 80 on the docker container and the docker
container should then bind the ports to the localhost.

**Comment by ramantalkin** [comment]
It looks like all services which are not working depended on apache for obvious reasons and apache fails beacuse of no data in configuration file

container# systemctl status http
● http.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
container# 

docker-host# cat /root/volumes/bitstation/etc/httpd/conf/httpd.conf
docker-host# 

working around !!

**Comment by joequant** [comment]
Ahhh....

What happens is that the image will dump the contents of /etc from the
image into the local disk the first time.  It will then use the contents of
the local disk version to persist changes.

The easiest thing to do is to just delete /root/volumes/bitstation and
rerun run-docker.sh

**Comment by ramantalkin** [comment]
This time got almost everything running, almost every thing and the application is still not resolving on any port. here it is my # systemctl 'http://imgur.com/a/kk67U'
certain services like resolvconf, ldconfig.service, network-up.service, partmon.service automatically exits upon restarting. It does not give error while restarting but when checking the status again, services exits (not fails).
Since network is not running, this might be the reason that system keeps on resolving web address. Would't it be better to use supervisor rather systemctl. systemctl known to have problems with docker. Also by using supervisor, the number of processes required to run the application could be reduced to absolute minimum.

**Comment by joequant** [comment]
Those services are not necessary and don't need to run so I'm pretty sure
that is a red herring.

The reason I'm using systemctl is that mageia is a systemctl based distro
and I didn't want to do anything strange to the image.

Can you see you can ping the VM?

**Comment by ramantalkin** [comment]
yes i can ping from docker host to docker container and vice versa but container does not resolve any web address like google dns 8.8.8.8

**Comment by joequant** [comment]
1) Does the container ping directly to 8.8.8.8?

If so then remove the volumes directory in the top level image and refresh.

If that doesn't work, then there might be something wrong with the image.
I'll push a new on over this evening.

**Comment by ramantalkin** [comment]
it worked by using --net=host flag with docker run command, thanks joequant, thank you for your support.
